CREATE TABLE IF NOT EXISTS estatisticas (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    alunos INT(11) UNSIGNED NOT NULL DEFAULT 0,
    projetos INT(11) UNSIGNED NOT NULL DEFAULT 0,
    polos INT(11) UNSIGNED NOT NULL DEFAULT 0,
    horas INT(11) UNSIGNED NOT NULL DEFAULT 0,
    data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)